# Generated by Django 5.0.6 on 2024-07-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAWSapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='F:/AWS_Project/sorry.jpg', upload_to='cars/'),
        ),
    ]
